apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: newildberries
  name: newildberries-db
  labels:
    app: newildberries-db

spec:
  replicas: 1
  selector:
    matchLabels:
      app: newildberries-db
  template:
    metadata:
      name: newildberries-db
      labels:
        app: newildberries-db
    spec:
      containers:
        - name: newildberries-db
          image: postgres:17-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_DB
              value: newildberries
            - name: POSTGRES_USER
              value: newildberries
            - name: POSTGRES_PASSWORD
              value: newildberries
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pgdata

      restartPolicy: Always

  volumeClaimTemplates:
    - metadata:
        name: pgdata
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi
