apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  namespace: newildberries
spec:
  serviceName: db
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
        - name: postgres
          image: postgres:17-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: newildberries
            - name: POSTGRES_USER
              value: newildberries
            - name: POSTGRES_PASSWORD
              value: newildberries
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pgdata
  volumeClaimTemplates:
    - metadata:
        name: pgdata
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi