apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: newildberries
  name: newildberries-app
  labels:
    app: newildberries-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newildberries-app
  template:
    metadata:
      name: newildberries-app
      labels:
        app: newildberries-app
    spec:
      containers:
        - name: newildberries-app
          image: alexmelory/newildberries
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
              protocol: TCP
          env:
            - name: POSTGRES_USER
              value: newildberries
            - name: POSTGRES_DB
              value: newildberries
            - name: POSTGRES_PASSWORD
              value: newildberries
            - name: POSTGRES_HOST
              value: newildberries-db-clusterip
            - name: POSTGRES_PORT
              value: "5432"
            - name: SUPPORT_EMAIL
              value: support@gmail.com
      restartPolicy: Always