apiVersion: v1
kind: Service
metadata:
  namespace: newildberries
  name: newildberries-app-loadbalancer
spec:
  selector:
    app: newildberries-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer